deliverables:
  - name: "HTML5"
    context:
      input: "../src/smartlayer-docsite.ditamap"
      profiles:
        ditavals: "no-implementer.ditaval"
    publication:
      transtype: "html5-bootstrap"
      params:
        - name: "args.hdr"
          href: "./smart-layer/navbar.xml"
        - name: "args.ftr"
          href: "./smart-layer/footer.xml"
        - name: "args.hdf"
          href: "./smart-layer/hdf.xml"
        - name: "args.css"
          value: "./smart-layer/custom.css"
        - name: "args.cssroot"
          path: "./"
        - name: "args.favicon"
          value: "favicon.ico"
        - name: "args.faviconpath"
          path: "./"
        - name: "args.faviconroot"
          path: "../config/smart-layer"
