deliverables:
- name: "HTML5"
  context:
    input: "../src/smartlayer.ditamap"
    profiles:
      ditavals: "no-implementer.ditaval"
  publication:
    transtype: "html5-bootstrap"
    params:
    - name: "args.hdr"
      href: "navbar.xml"
    - name: "args.ftr"
      href: "footer.xml"
    - name: "args.hdf"
      href: "hdf.xml"
    - name: "args.css"
      value: "custom.css"
    - name: "args.cssroot"
      path: "./"
    - name: "args.favicon"
      value: "favicon.ico"
    - name: "args.faviconpath"
      path: "./"
    - name: "args.faviconroot"
      path: "../src"
